# Generated by Django 5.2.6 on 2026-09-15 00:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioDeRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('series_objetivo', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('repeticiones_objetivo', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('peso_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('descanso_segundos', models.PositiveIntegerField(default=90)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_rutinas', to='ejercicios.ejercicio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
