# Generated by Django 5.2.6 on 2026-09-15 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejercicioderutina',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_rutina', to='rutinas.rutina'),
        ),
        migrations.AddConstraint(
            model_name='ejercicioderutina',
            constraint=models.UniqueConstraint(fields=('rutina', 'ejercicio'), name='ejercicio_unico_por_rutina'),
        ),
    ]
