# Generated by Django 5.2.6 on 2026-09-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('icono', models.CharField(default='link', max_length=40)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
