# Generated by Django 5.2.6 on 2026-09-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_ejercicio', models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('movilidad', 'Movilidad'), ('calistenia', 'Calistenia')], default='fuerza', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('equipamiento', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grupo_muscular__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
