# Generated by Django 5.2.6 on 2026-09-15 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejercicios', to='ejercicios.grupomuscular'),
        ),
        migrations.AddConstraint(
            model_name='ejercicio',
            constraint=models.UniqueConstraint(fields=('nombre', 'grupo_muscular'), name='ejercicio_nombre_grupo_unico'),
        ),
    ]
