# Generated by Django 5.2.6 on 2026-09-15 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ejercicio',
            name='ejercicio_nombre_grupo_unico',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ejercicio',
            constraint=models.UniqueConstraint(condition=models.Q(('propietario__isnull', True)), fields=('nombre', 'grupo_muscular'), name='ejercicio_catalogo_nombre_grupo_unico'),
        ),
        migrations.AddConstraint(
            model_name='ejercicio',
            constraint=models.UniqueConstraint(fields=('nombre', 'grupo_muscular', 'propietario'), name='ejercicio_usuario_nombre_grupo_unico'),
        ),
    ]
