# Generated by Django 5.2.6 on 2026-09-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_remove_ejercicio_ejercicio_nombre_grupo_unico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='alias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='autor_fuente',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='categoria_fuente',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='consejos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='fuente',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='licencia_nombre',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='licencia_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='musculos_principales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='musculos_secundarios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tempo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
