# Generated by Django 5.2.6 on 2026-09-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0004_ejercicio_alias_ejercicio_autor_fuente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
