# Generated by Django 5.2.6 on 2026-09-15 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=7)),
                ('repeticiones', models.PositiveIntegerField()),
                ('logrado_en', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ejercicios.ejercicio')),
            ],
            options={
                'ordering': ['-peso', '-logrado_en'],
            },
        ),
    ]
