# Generated by Django 5.2.6 on 2026-09-15 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progreso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpersonal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='recordpersonal',
            constraint=models.UniqueConstraint(fields=('usuario', 'ejercicio', 'peso', 'repeticiones'), name='record_unico'),
        ),
    ]
