# Generated by Django 5.2.6 on 2026-09-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('entero', 'Entero'), ('decimal', 'Decimal'), ('booleano', 'Booleano')], default='texto', max_length=10)),
                ('obligatorio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('cuerpo', models.TextField()),
                ('publicado', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
