# Generated by Django 5.2.6 on 2026-09-15 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='SerieEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=7)),
                ('repeticiones', models.PositiveIntegerField()),
                ('descanso_segundos', models.PositiveIntegerField(default=0)),
                ('completado_en', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_registradas', to='ejercicios.ejercicio')),
            ],
            options={
                'ordering': ['ejercicio', 'numero_serie'],
            },
        ),
    ]
