# Generated by Django 5.2.6 on 2026-09-15 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrenamientos', '0001_initial'),
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='rutinas.rutina'),
        ),
    ]
