# Generated by Django 5.2.6 on 2026-09-15 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrenamientos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serieentrenamiento',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='entrenamientos.sesionentrenamiento'),
        ),
        migrations.AddConstraint(
            model_name='serieentrenamiento',
            constraint=models.UniqueConstraint(fields=('sesion', 'ejercicio', 'numero_serie'), name='serie_numero_unico'),
        ),
    ]
