# Generated by Django 5.2.6 on 2026-09-15 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('correr', 'Correr'), ('ciclismo', 'Ciclismo'), ('natacion', 'Natación'), ('caminar', 'Caminar'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('realizada_en', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=0)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calorias', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-realizada_en'],
            },
        ),
    ]
