# Generated by Django 5.2.6 on 2026-09-15 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0004_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='archivo_gpx',
            field=models.FileField(blank=True, upload_to='gpx/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='datos_elevacion',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='actividad',
            name='datos_ruta',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='actividad',
            name='distancia_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='elevacion_ganada_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='elevacion_perdida_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SegmentoKilometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('distancia_metros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion_segundos', models.PositiveIntegerField()),
                ('ritmo_segundos_km', models.PositiveIntegerField(blank=True, null=True)),
                ('elevacion_ganada_m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('elevacion_perdida_m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='entrenamientos.actividad')),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('actividad', 'numero'), name='segmento_km_unico')],
            },
        ),
    ]
