# Generated by Django 5.2.6 on 2026-09-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objetivo', models.CharField(choices=[('ganancia_muscular', 'Ganancia muscular'), ('fuerza', 'Fuerza'), ('perdida_grasa', 'Pérdida de grasa'), ('condicion_fisica', 'Condición física'), ('mantenimiento', 'Mantenimiento')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-activo', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro'), ('prefiero_no_decirlo', 'Prefiero no decirlo')], max_length=30)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nivel_experiencia', models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('frecuencia_entrenamiento', models.CharField(blank=True, choices=[('1', '1 días por semana'), ('2', '2 días por semana'), ('3', '3 días por semana'), ('4', '4 días por semana'), ('5', '5 días por semana'), ('6', '6 días por semana'), ('7', '7 días por semana')], max_length=1)),
            ],
        ),
    ]
